import React from "react";
import Head from "next/head";
import PledgeCard from "components/pledgeCard/PledgeCard";
import { usePledges } from "api-client/api-client-query";

export default function Home() {
  const { data, error, isLoading } = usePledges({});
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {data?.pledges?.items?.map((pledge) => (
            <PledgeCard
              pledge={pledge}
              entity={{}}
              author={{}}
              key={pledge.id}
            />
          ))}
        </div>
      </main>
    </>
  );
}
