import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import PledgeCard from "components/pledgeCard/PledgeCard";
import { usePledges } from "api-client/api-client-query";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const { data, error, isLoading } = usePledges({
    page: 1,
    count: 25,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {data?.pledges?.items?.map((pledge) => (
            <PledgeCard
              pledge={pledge}
              entity={{}}
              author={{}}
              key={pledge.id}
            />
          ))}
        </div>
      </main>
    </>
  );
}
